version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /minos_adjudicate.wdl
    testParameterFiles:
      - /minos_adjudicate.json
    authors:
      - orcid: 0000-0003-4896-1858
    name: minos_adjudicate